### ISSUE TITLE
[Feature] Add -n option for confirmation inputs

### ISSUE THREAD

**Issue by calebkleveter** [vapor/console#51]
We can pass in a `-y` flag to automatically answer `yes` to a confirmation dialogue.  I think it would be helpful to add a `-n` flag to automatically answer `no`. This could be useful if we need to regenerate an Xcode project the toolbox and don't want to re-open it:

    vapor xcode -n

**Comment by tanner0101** [comment]
This should be fixed in 3.1.3! :)
