### ISSUE TITLE
Command Options ask for a new option syntax, but can’t actually use it.

### ISSUE THREAD

**Issue by EricWVGG** [vapor/console#77]
sample project: https://github.com/EricWVGG/vapor-command-problem

This command runs correctly, but returns a warning…

`vapor run quiz --answer=one`
warning: `[Deprecated] --option=value syntax is deprecated. Please use --option value (with no =) instead.`

If we follow those directions…

`vapor run quiz --answer one`
we get `Fatal error: Error raised at top level: ⚠️ CommandError: Too many arguments or unsupported options were supplied: ["one"]`

**Comment by joscdk** [comment]
It's most likely because of the toolbox, as it's still running Vapor 2, try to run directly through the executable in your app, and the new way setting arguments should work

**Comment by EricWVGG** [comment]
`swift run Run quiz --answer one` … yup, you're correct. Thank you.
