### ISSUE TITLE
Value Validation

### ISSUE THREAD

**Issue by calebkleveter** [vapor/console#87]
Add a `validation` property to `CommandArgument` and `CommandOption` which is an array of `(Sting)throws -> Void` that validates the values when they are parsed from input.

It would look something like this:

```swift
CommandArgument(name: "times", default: "1",  validations: [isInt])

let isInt: (String)throws -> Void = { times in
    guard Int(times) != nil else {
        throw CommandError(identifier: "validationFailed", reason: "Cannot convert value `\(times)` to Int"
    }
}
```

This value would be assigned an empty array by default, so it would not be a breaking change.

**Comment by tanner0101** [comment]
I like this idea 👍 

Another idea for how this could work is having `CommandArgument`'s value type be generic. So you could set it as something like `enum Foo: String { }` and get free validation.
