### ISSUE TITLE
Type-Safe Input

### ISSUE THREAD

**Issue by calebkleveter** [vapor/console#91]
https://gist.github.com/calebkleveter/9f269d8f5323f2a4679be53e57939c9e

**Note:** This issue will be fleshed out more when I have time.

**Comment by tanner0101** [comment]
One caveat to consider with this implementation vs. the `enum` based one is that each call to get an option or argument (i.e., `let name = try context.argument(\.name)`) is passing around the entire `Argument` struct, including all of the help and name strings.

The enum approach on the other hand, although a bit more verbose, would only access the name, help, or short flag as needed (computed property) which seems a little cleaner.

```swift
class SomeCommand: Command {
    enum Arguments: String, CommandArgument {
        case string, count

        var help: String? {
            switch self {
            case .string: return "The string to print to srdout"
            case .count: "The number of times to output the string"
            }
        }
    }
    
    enum Options: CommandOption {
        case verbose

        var help: String? {
            switch self {
            case .verbose: return "List each output on its own line"
            }
        }

        var shortFlag: Character? {
            switch self {
            case .verbose: return "v"
            }
        }
    }
  
    func run(on context: CommandContext<SomeCommand>)throws -> Future<Void> {
        let name = try context.argument(.name)
        let count = try context.argument(.count)
        
        if try context.options(.verbose) {
            (1...count).forEach { _ in print(name) }
        } else {
            print(String(repeating: name, count: count))
        }
        
        return Future(())
    }
}
```

Here when you call `let name = try context.argument(.name)` only the enum value (probably a single byte) is being passed. There's also no KeyPath required.

**Comment by calebkleveter** [comment]
https://forums.swift.org/t/pitch-type-safe-input/21650
